### ISSUE TITLE
Cache concurrency question

### ISSUE THREAD

**Issue by clibequilibrium** [Marplex/flarebase-auth#5]
- **I'm submitting a question about the decisions made in the repository

Hi I see that you use 3600 seconds to cache OAuth token in Cloudflare KV. Since KV is eventual consistent is there a potential for token being refreshes multiple times  (if multiple requests are served concurrently) which would invalidate the previous token. In other words how battle tested this cache implementation is ? Thank you.

**Comment by Marplex** [comment]
Thanks for the comment! I didn't really think about it when implementing the cache part, I saw it more as a generic module rather than specific to Cloudflare KV. Right now the CloudflareKV implementation is not battle tested and, as you said, it may cause multiple token refreshes until it becomes consistent. 

You can still swap it with your own cache implementation, or push a PR if you have time to fix the current one :+1:

**Comment by clibequilibrium** [comment]
> Thanks for the comment! I didn't really think about it when implementing the cache part, I saw it more as a generic module rather than specific to Cloudflare KV. Right now the CloudflareKV implementation is not battle tested and, as you said, it may cause multiple token refreshes until it becomes consistent.
> 
> You can still swap it with your own cache implementation, or push a PR if you have time to fix the current one 👍

Thank you ! I am currently trying Durable Objects for strong consistency and might submit a PR as another cache option as soon as I master it.

**Comment by clibequilibrium** [comment]
@Marplex for simple fetch you can use  { cf: { cacheTtl } }

```
async function getPublicKey(): Promise<string> {
	const res = await fetch('https://www.googleapis.com/identitytoolkit/v3/relyingparty/publicKeys', {
		cf: {
			cacheTtl: GOOGLE_PUBLIC_KEY_CACHE_TIME,
			cacheEverything: true
		}
	});
	return await res.text();
}
```

It worked perfectly for me avoiding frequent KV reads . 

As for POSTs you can cache post requests including auth tokens

https://developers.cloudflare.com/workers/examples/cache-post-request/
