### ISSUE TITLE
Question on uid after verifySessionCookie

### ISSUE THREAD

**Issue by santoshv98** [Marplex/flarebase-auth#6]
- **I'm submitting a .
 question about how to use this project

- **Summary**

How do I find out uid after performing a verifySessionCookie? The sdk verifySessionCookie returns an object thats different from your DecodedIDToken, so I am not able to understand how I can get uid (firebase's identifier for the user)?

verifySessionCookie - is it verifying offline just by decoding jwt and NOT making any real requests to FB Http API. Can you pl confirm?

**Comment by clibequilibrium** [comment]
> * **I'm submitting a .
>   question about how to use this project
> * **Summary**
> 
> How do I find out uid after performing a verifySessionCookie? The sdk verifySessionCookie returns an object thats different from your DecodedIDToken, so I am not able to understand how I can get uid (firebase's identifier for the user)?
> 
> verifySessionCookie - is it verifying offline just by decoding jwt and NOT making any real requests to FB Http API. Can you pl confirm?

It's token.sub as stated in https://jwt.io/introduction

As for verficitaion, read the code there is no checkRevoked code path.
