### ISSUE TITLE
How to deploy on Cloudflare Worker?

### ISSUE THREAD

**Issue by prilaga** [Marplex/flarebase-auth#7]
@Marplex @arlair 
Please share instructions how to deploy these library on Cloudflare Worker.
It will be very helpful.
Thanks.

**Comment by prilaga** [comment]
@Marplex @arlair I receive next errors:

flarebase-auth.ts:1:61: ERROR: Could not resolve "jose"
src/lib/google-oauth.ts:8:7: ERROR: Could not resolve "jose"

**Comment by clibequilibrium** [comment]
> @Marplex @arlair I receive next errors:
> 
> flarebase-auth.ts:1:61: ERROR: Could not resolve "jose" src/lib/google-oauth.ts:8:7: ERROR: Could not resolve "jose"

the error clearly states that you are missing library jose for JSON support. 

Do
`npm i jose`
